# Generated by Django 4.2.20 on 2025-08-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("membro", "Membro"),
                    ("visualizador", "Visualizador"),
                ],
                default="membro",
                max_length=20,
            ),
        ),
    ]
