# Generated by Django 5.2.1 on 2025-08-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroequipe',
            name='papel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('membro', 'Membro')], default='membro', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('membro', 'Membro')], default='membro', max_length=20),
        ),
    ]
