# Generated by Django 5.2.1 on 2025-08-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_remove_visualizador_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statustarefa',
            unique_together={('nome',)},
        ),
        migrations.AlterField(
            model_name='statustarefa',
            name='ordem',
            field=models.PositiveIntegerField(verbose_name='Ordem'),
        ),
        migrations.RemoveField(
            model_name='statustarefa',
            name='equipe',
        ),
    ]
